[project]
name = "ai-prof"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AshokYekkanti754", email = "ashokyekkanti737@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn>=0.52.4",
]

[project.scripts]
ai-prof = "ai_prof:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
